version: '3.3'
services:
  elasticsearch:
    build:
      context: ./elasticsearch
    container_name: elasticsearch
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - front

  kibana:
    build:
      context: ./kibana
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - front

networks:
  front:
    driver: bridge    
